<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
    die();

$GLOBALS['AQW_STORE']['IBLOCK_ID'] = "#AQW_SHOP_PRODUCTS#";
$GLOBALS['AQW_STORE']['LINK_IBLOCK_ID'] = "#AQW_SHOP_OFFERS#";
$GLOBALS['AQW_BRANDS']['IBLOCK_ID'] = "#AQW_SHOP_VENDOR#";
$GLOBALS['AQW_ORDER']['IBLOCK_ID'] = "#AQW_SHOP_ORDERS#";
$GLOBALS['AQW_ORDER']['IBLOCK_TYPE'] = "ORDERS";

?>